# AUTOGENERATED BY: ProsperCookiecutters/ProsperFlask
# TEMPLATE VERSION: {{cookiecutter.template_version}}
# AUTHOR: {{cookiecutter.author_name}}

"""PyTest fixtures and modifiers"""

import pytest

from {{cookiecutter.library_name}}.endpoints import APP

@pytest.fixture
def app():
    """flask test hook for dry-running Flask code"""
    return APP
