"""
AUTOGENERATED BY: ProsperCookiecutters/ProsperFlask
TEMPLATE VERSION: {{cookiecutter.template_version}}

Setup.py: Packaging requirements for {{cookiecutter.project_name}}
"""
from codecs import open
import importlib

from setuptools import setup, find_packages
from setuptools.command.test import test as TestCommand


__package_name__ = '{{cookiecutter.project_name}}'
__library_name__ = '{{cookiecutter.library_name}}'

def get_version(package_name):
    """find __version__ for making package

    Args:
        package_name (str): path to _version.py folder (abspath > relpath)

    Returns:
        str: __version__ value

    """
    module = package_name + '._version'
    package = importlib.import_module(module)

    version = package.__version__

    return version


class PyTest(TestCommand):
    """PyTest cmdclass hook for test-at-buildtime functionality

    http://doc.pytest.org/en/latest/goodpractices.html#manual-integration

    """
    user_options = [('pytest-args=', 'a', 'Arguments to pass to pytest')]

    def initialize_options(self):
        TestCommand.initialize_options(self)
        self.pytest_args = [
            'tests',
            '-rx',
            '--cov=' + __library_name__,
            '--cov-report=term-missing',
            '--cov-config=.coveragerc',
        ]

    def run_tests(self):
        import shlex
        import pytest
        pytest_commands = []
        try:
            pytest_commands = shlex.split(self.pytest_args)
        except AttributeError:
            pytest_commands = self.pytest_args
        errno = pytest.main(pytest_commands)
        exit(errno)

class QuickTest(PyTest):
    """wrapper for quick-testing for devs"""
    def initialize_options(self):
        TestCommand.initialize_options(self)
        self.pytest_args = [
            'tests',
            '-rx',
            '-n',
            '4',
            '--cov=' + __library_name__,
            '--cov-report=term-missing',
            '--cov-config=.coveragerc',
        ]

class TravisTest(PyTest):
    """wrapper for quick-testing for devs"""
    def initialize_options(self):
        TestCommand.initialize_options(self)
        self.pytest_args = [
            'tests',
            '-rx',
            '--junitxml=/tmp/datareader.xml',
            '--cov=' + __library_name__,
            '--cov-report=term-missing',
            '--cov-config=.coveragerc',
        ]

with open('README.rst', 'r', 'utf-8') as f:
    README = f.read()

setup(
    name=__package_name__,
    author='{{cookiecutter.author_name}}',
    author_email='{{cookiecutter.author_email}}',
    url='https://github.com/{{cookiecutter.github_name}}/' + __package_name__,
    download_url='https://github.com/{{cookiecutter.github_name}}/' + __package_name__ + '/tarball/v' + get_version(__library_name__),
    version=get_version(__library_name__),
    description='{{cookiecutter.project_brief}}',
    long_description=README,
    keywords='{{cookiecutter.keywords}}',
    license='MIT',
    classifiers=[
        'Programming Language :: Python :: 3.6'
    ],

    packages=find_packages(),
    include_package_data=True,
    package_data={
        '': ['LICENSE', 'README.rst'],
        __library_name__: ['version.txt', 'app.cfg']
    },
    entry_points={
        'console_scripts': [
            'launcher_{{cookiecutter.project_name}}={{cookiecutter.library_name}}.launcher_{{cookiecutter.project_name}}:run_main',
        ]
    },
    install_requires=[
        'ProsperCommon',
        'plumbum',
        'Flask',
        'flask-restplus',
    ],
    tests_require=[
        'pytest',
        'pytest_cov',
        'pytest-xdist',
        'pytest-flask',
        'docker',
    ],
    extras_require={
        'dev':[
            'sphinx',
            'sphinxcontrib-napoleon',
            'semantic-version',
        ]
    },
    cmdclass={
        'test':PyTest,
        'fast': QuickTest,
        'travis': TravisTest,
    }
)
